Unit Testing
felixDev22/school_library pull request #7
Opened 2023-03-22 18:28 UTC by bernabasy

RUBY / DATABASES AND INTERVIEWING: [OOP school library: unit tests](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_unit_tests.md)
- Add unit tests for all the methods in all the classes to:
   Book
   Person
   Student
   Teacher
   Classroom
   Rental
 - All classes that you created while implementing the Decorator design pattern.

2023-03-22 18:52 UTC, danmainah requested changes
Hi @bernabasy and @felixDev22 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Gitflow was correctly used
✔️  Good design


# Required Changes ♻️
- [ ] @bernabasy and @felixDev22 kindly ensure your issues page link in the reader file is working correctly currently it's broken
![image](https://user-images.githubusercontent.com/61408860/227004487-b25348c0-3d53-49a5-a587-c700baf29cf1.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-22 18:52 UTC, danmainah commented on spec/book_spec.rb
> +end
- [ ] @team great job on your tests, however, you forgot to add tests for the `add_rental` and `to_h` methods , its a project requirement to have unit tests for all methods in a class.

2023-03-22 18:52 UTC, danmainah commented on spec/person_spec.rb
> +  end
- [x] @team great job on your tests, however, you forgot to add tests for the `add_rental`, `correct_name`, `can_use_services?`, `of_age?` and `to_h` methods, its a project requirement to have unit tests for all methods in a class.

2023-03-22 18:52 UTC, danmainah commented on spec/student_spec.rb
> +end
- [ ]  @team great job on your tests, however, you forgot to add tests for `classroom=` method, it's a project requirement to have unit tests for all methods in a class.

2023-03-22 18:52 UTC, danmainah commented on spec/rental_spec.rb
> +  end
- [ ] @team great job on your tests, however, you forgot to add a test for the  `to_h` method, its a project requirement to have unit tests for all methods in a class.

2023-03-23 19:32 UTC, zainsadaqat approved these changes
# Pull Request Approved ✅ 🎊 🎉 
## Hello Team!👋 

## Things to Appreciate 
- [ ] Correct Flow ✅ 
- [ ] Clean Code 👍 
- [ ] No Linter Errors 🔥 
- [ ] Descriptive Pull Request and Summary 👌 

### Your project is complete!  There is nothing else to say other than it's time to merge it.

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 ☑️ 

<img src="https://media4.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 19:43 UTC, merged